title = "Project Confgiuration"

[database]
host = "localhost"
name = "hearings"
user = "postgres"
table_config_path = "table_config.sql"

[data]
committee_path = "gpo_tools/gpo_tools/data/committee_data.csv"
house_assignment_path = "gpo_tools/gpo_tools/data/house_assignments_103-115-1.csv"
senate_assignment_path = "gpo_tools/gpo_tools/data/senate_assignments_103-115-1.csv"
