title = "Project Confgiuration"

[old_postgres]
host = "localhost"
name = "hearings"
user = "postgres"
table_config_path = "table_config.sql"

[sqlite]
db_driver = 'sqlite'
db_filepath = ''

[govinfo_db]
db_type = 'postgresql'
db_driver = 'psycopg2'
host = 'localhost'
name = 'govinfo'
user = 'postgres'

[data]
committee_path = "chrg_tools/metadata_migration/committee_metadata/committee_data.csv"
house_assignment_path = "chrg_tools/metadata_migration/committee_metadata/house_assignments_103-115-1.csv"
senate_assignment_path = "chrg_tools/metadata_migration/committee_metadata/senate_assignments_103-115-1.csv"

[mongodb]
uri = 'mongodb://localhost'
